application: nickotterportfolio
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
  
- url: /services/.*
  script: services.app
  
- url: /.*
  script: index.app
  
libraries:
- name: jinja2
  version: latest