application: nickotterportfolio
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
  
- url: /javascript
  static_dir: javascript
  
- url: /images
  static_dir: images
  
- url: /services/.*
  script: services.app
  
- url: /resume/
  script: resume.app

- url: /.*
  script: index.app
  
libraries:
- name: jinja2
  version: latest